name: sentiment-bow
channels:
  - conda-forge      
  - defaults
dependencies:
  - python=3.12      
  - scikit-learn
  - pandas
  - numpy
  - nltk*
  - bz2file
  - jupyterlab  
  - notebook   
  - matplotlib
  - pip              
  - pip:
      - kagglehub
